### ISSUE TITLE
file not found error when zipping the /config folder.

### ISSUE THREAD

**Issue by Jessassin** [SKCraft/SKMCLauncher#51] opened 2013-06-12 21:06 UTC
This error seems to be caused by uppercase characters being replaced by lowercase ones, resulting in a "file not found" error. This exists in build #56 from build.sk89q.com

![image](https://f.cloud.github.com/assets/1862974/645415/f6c25662-d3a3-11e2-9454-2c8d51786ae2.png)

**Comment by sk89q** [comment] 2013-06-12 23:54
I think it was caused by you placing the archive in config/, and maybe config/ didn't exist in the target folder. Wish there was a stack trace.

Does the newest build fix it?
http://build.sk89q.com/job/SKMCLauncher/57/

**Comment by Graloth** [comment] 2013-06-13 09:16
I've tried with the latest successful build as well as the one you linked, it seems a similar error happens in both (changing letter case). It tries to access a file by it's name in all lowercase, though it's only available with the capital letters.

> Downloading http://arduard.com/hardmode/config/unlittorch.cfg...
> Downloading to C:\Users\*************\AppData\Roaming\.minecraft\instances\arduard.com_arduard-hardmode.minecraft_download_4ce64c6fbfa643440e97aea4da758b57.download...
> Failed to download http://arduard.com/hardmode/config/unlittorch.cfg

The correct path to the config is http://arduard.com/hardmode/config/UnlitTorch.cfg

Any help would be greatly appreciated, as I would like to use your launcher to distribute a modpack amongst friends but this error is preventing the "install from URL" as well as the update functionality from working as intended

**UPDATE**

Looked some more into it, and found out that the package.xml that the launcher generates when you want to make your own install for a modpack etc. it converts all foldernames and filenames in /config to lowercase, except it doesn't do it for the files themselves, only their reference

**Comment by sk89q** [comment] 2013-06-21 19:00
Is it possible to give me a bare minimum set of files that break?

**Comment by jakimfett** [comment] 2013-06-21 22:28
A note on this: If you build the pack via the GUI, and de-select the zip configs option, the file paths in package.xml are NOT converted to lowercase, and they have "<file></file>" tags instead of "<archive></archive>" tags. See http://picraft.com/pitek/package.xml vs http://mc.picraft.com/bleeding/package.xml

**Comment by sk89q** [comment] 2013-06-21 22:51
Fixed now, I believe.

#56 has reason

**Closed as completed by sk89q** 2013-06-21 22:51 UTC
